ORDERS = {
    "ORD001": {
        "id": "ORD001",
        "product": "Samsung 43\" Smart TV",
        "status": "delivered",
        "amount": 29999,
        "order_date": "2026-04-20",
        "delivery_date": "2026-04-26",
        "carrier": "Delhivery",
        "tracking": "DL1234567890",
        "return_eligible": True,
    },
    "ORD002": {
        "id": "ORD002",
        "product": "Nike Air Max Running Shoes",
        "status": "in_transit",
        "amount": 7499,
        "order_date": "2026-04-26",
        "expected_delivery": "2026-04-30",
        "carrier": "Blue Dart",
        "tracking": "BD9876543210",
        "last_location": "Mumbai Sorting Hub",
        "return_eligible": False,
    },
    "ORD003": {
        "id": "ORD003",
        "product": "iPhone 15 Silicone Case - Blue",
        "status": "delayed",
        "amount": 1299,
        "order_date": "2026-04-24",
        "original_delivery": "2026-04-28",
        "new_expected_delivery": "2026-05-02",
        "delay_reason": "Weather disruption at origin hub",
        "carrier": "DTDC",
        "return_eligible": False,
    },
    "ORD004": {
        "id": "ORD004",
        "product": "Preethi Mixer Grinder 750W",
        "status": "cancelled",
        "amount": 4599,
        "order_date": "2026-04-22",
        "cancellation_date": "2026-04-23",
        "cancellation_reason": "Customer requested cancellation",
        "refund_status": "initiated",
        "refund_eta": "2026-05-03",
        "return_eligible": False,
    },
    "ORD005": {
        "id": "ORD005",
        "product": "Libas Women's Kurta Set",
        "status": "return_initiated",
        "amount": 899,
        "order_date": "2026-04-15",
        "return_ticket": "RT005678",
        "pickup_date": "2026-05-01",
        "return_reason": "Size mismatch",
        "return_eligible": False,
    },
    "ORD006": {
        "id": "ORD006",
        "product": "boAt Airdopes 141 Bluetooth Earbuds",
        "status": "refund_processed",
        "amount": 1299,
        "order_date": "2026-04-10",
        "refund_amount": 1299,
        "refund_date": "2026-04-27",
        "refund_method": "Snapdeal Wallet",
        "return_eligible": False,
    },
}

PRODUCTS = [
    {"id": "P001", "name": "Samsung 43\" Smart TV", "price": 29999, "category": "Electronics", "in_stock": True, "rating": 4.3, "seller": "TechZone"},
    {"id": "P002", "name": "boAt Airdopes 141 Bluetooth Earbuds", "price": 1299, "category": "Electronics", "in_stock": True, "rating": 4.1, "seller": "AudioHub"},
    {"id": "P003", "name": "Redmi Note 13 Pro (8GB/256GB)", "price": 22999, "category": "Electronics", "in_stock": False, "rating": 4.4, "seller": "MobiZone"},
    {"id": "P004", "name": "Logitech MK235 Wireless Keyboard & Mouse", "price": 1895, "category": "Electronics", "in_stock": True, "rating": 4.2, "seller": "TechZone"},
    {"id": "P005", "name": "TP-Link AC750 WiFi Router", "price": 1599, "category": "Electronics", "in_stock": True, "rating": 4.0, "seller": "NetStore"},
    {"id": "P006", "name": "Nike Air Max Running Shoes", "price": 7499, "category": "Clothing", "in_stock": True, "rating": 4.5, "seller": "SportsGear"},
    {"id": "P007", "name": "Libas Women's Kurta Set", "price": 899, "category": "Clothing", "in_stock": True, "rating": 3.9, "seller": "FashionHub"},
    {"id": "P008", "name": "Levis 511 Slim Jeans", "price": 2599, "category": "Clothing", "in_stock": True, "rating": 4.3, "seller": "DenimWorld"},
    {"id": "P009", "name": "Woodland Men's Casual Shoes", "price": 3299, "category": "Clothing", "in_stock": False, "rating": 4.1, "seller": "ShoeHub"},
    {"id": "P010", "name": "Allen Solly Formal Shirt", "price": 1299, "category": "Clothing", "in_stock": True, "rating": 4.0, "seller": "FashionHub"},
    {"id": "P011", "name": "Preethi Mixer Grinder 750W", "price": 4599, "category": "Home & Kitchen", "in_stock": True, "rating": 4.4, "seller": "HomeAppliances"},
    {"id": "P012", "name": "Milton Thermosteel Flask 1L", "price": 649, "category": "Home & Kitchen", "in_stock": True, "rating": 4.2, "seller": "KitchenStore"},
    {"id": "P013", "name": "Prestige Hard Anodised Kadai 3L", "price": 1299, "category": "Home & Kitchen", "in_stock": True, "rating": 4.3, "seller": "KitchenStore"},
    {"id": "P014", "name": "Cello Opalware Dinner Set (18 pcs)", "price": 1899, "category": "Home & Kitchen", "in_stock": False, "rating": 4.1, "seller": "HomeDecor"},
    {"id": "P015", "name": "Pigeon Aluminium Pressure Cooker 5L", "price": 1349, "category": "Home & Kitchen", "in_stock": True, "rating": 4.0, "seller": "HomeAppliances"},
    {"id": "P016", "name": "iPhone 15 Silicone Case - Blue", "price": 1299, "category": "Electronics", "in_stock": True, "rating": 4.2, "seller": "CaseStore"},
]

ACCOUNTS = {
    "user@example.com": {
        "name": "Rahul Sharma",
        "email": "user@example.com",
        "status": "active",
        "wallet_balance": 1299,
        "recent_orders": ["ORD001", "ORD002", "ORD003"],
        "member_since": "2023-06-15",
    },
    "demo@snapdeal.com": {
        "name": "Priti Verma",
        "email": "demo@snapdeal.com",
        "status": "active",
        "wallet_balance": 0,
        "recent_orders": ["ORD004", "ORD005", "ORD006"],
        "member_since": "2024-01-20",
    },
}
